on: [push, workflow_dispatch]

jobs:
  #deploy-runner:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #
  #    - uses: iterative/setup-cml@v1
  #
  #    - name: deploy
  #       shell: bash
  #      env:
  #        REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  #        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #      run: |
  #        cml-runner \
  #        --cloud aws \
  #        --cloud-region us-west \
  #        --cloud-type=g3.4xlarge \
  #        --cloud-hdd-size 64 \ 
  #        --labels=cml-runner

  model-training:
    # needs: deploy-runner
    runs-on: [self-hosted, cml-runner]
    container: 
      image: docker://spr3n/torch:latest
      options: --gpus all

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
      
      - name: cml
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }} 
        run: |
          # DVC stuff
          git fetch --prune
          dvc init
          dvc repro
          /opt/conda/bin/python examples/synthetic_s3.py
          
          echo "# 3D Convolutional Net" >> report.md
          # Does not see images saved by `examples/synthetic_s3.py`
          echo $(ls ./examples) 
          cml-publish examples/loss.png --md >> report.md
          cml-send-comment report.md 
